# Generated by Django 4.0.4 on 2022-04-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizayner', '0002_portfolio_portfolio_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizayner',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='dizayner',
            name='telephone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
