# Generated by Django 4.0.4 on 2022-04-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizayner', '0003_dizayner_email_dizayner_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_photo',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
