# Generated by Django 4.0.4 on 2022-05-13 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dizayner', '0004_alter_portfolio_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_photo',
            name='description',
            field=models.TextField(blank=b'I01\n', default='', verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Proizvoditeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='static/photo/%Y/%m/%d/', verbose_name='фото дизайнера')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(default='', max_length=254)),
                ('telephone', models.CharField(default='', max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Производитель')),
            ],
        ),
    ]
